version: '2'
services:
  diplomovka-docker-app: 
    image: therdvn/diplomovka-docker-app:latest
    container_name: diplomovka_app
    restart: always
    privileged: true
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: 50m
        max-file: "3"
        labels: "spring-boot-app"
        env: "base"
    networks:
      default:
        aliases:
          - docker_app

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
